"""baseline schema.

Revision ID: b4f9d85b73e3
Revises:
Create Date: 2026-05-02 01:08:01.393927
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b4f9d85b73e3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bulk_block_deals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("deal_date", sa.Date(), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=True),
        sa.Column("buy_sell", sa.String(length=8), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("deal_type", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "deal_date", "client_name", "deal_type", "quantity", name="uq_bulk_block_deal"
        ),
    )
    op.create_index(
        op.f("ix_bulk_block_deals_deal_date"), "bulk_block_deals", ["deal_date"], unique=False
    )
    op.create_index(
        op.f("ix_bulk_block_deals_symbol"), "bulk_block_deals", ["symbol"], unique=False
    )
    op.create_table(
        "composite_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("band", sa.String(length=40), nullable=True),
        sa.Column("fundamentals_score", sa.Float(), nullable=True),
        sa.Column("technicals_score", sa.Float(), nullable=True),
        sa.Column("flows_score", sa.Float(), nullable=True),
        sa.Column("events_quality_score", sa.Float(), nullable=True),
        sa.Column("macro_sector_score", sa.Float(), nullable=True),
        sa.Column("active_signal_count", sa.Integer(), nullable=False),
        sa.Column("active_signals_json", sa.Text(), nullable=False),
        sa.Column("reasons_json", sa.Text(), nullable=False),
        sa.Column("risks_json", sa.Text(), nullable=False),
        sa.Column("missing_data_json", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "as_of_date", "source", name="uq_composite_score_symbol_date"
        ),
    )
    op.create_index(
        op.f("ix_composite_scores_as_of_date"), "composite_scores", ["as_of_date"], unique=False
    )
    op.create_index(
        op.f("ix_composite_scores_symbol"), "composite_scores", ["symbol"], unique=False
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "ex_date", "action_type", name="uq_corporate_action"),
    )
    op.create_index(
        op.f("ix_corporate_actions_ex_date"), "corporate_actions", ["ex_date"], unique=False
    )
    op.create_index(
        op.f("ix_corporate_actions_symbol"), "corporate_actions", ["symbol"], unique=False
    )
    op.create_table(
        "delivery_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("series", sa.String(length=8), nullable=True),
        sa.Column("traded_qty", sa.Float(), nullable=True),
        sa.Column("deliverable_qty", sa.Float(), nullable=True),
        sa.Column("delivery_pct", sa.Float(), nullable=True),
        sa.Column("turnover_lacs", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "trade_date", name="uq_delivery_data"),
    )
    op.create_index(op.f("ix_delivery_data_symbol"), "delivery_data", ["symbol"], unique=False)
    op.create_index(
        op.f("ix_delivery_data_trade_date"), "delivery_data", ["trade_date"], unique=False
    )
    op.create_table(
        "instrument_master",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("instrument_token", sa.Integer(), nullable=False),
        sa.Column("exchange_token", sa.Integer(), nullable=True),
        sa.Column("tradingsymbol", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("exchange", sa.String(length=16), nullable=False),
        sa.Column("segment", sa.String(length=32), nullable=True),
        sa.Column("instrument_type", sa.String(length=32), nullable=True),
        sa.Column("tick_size", sa.Float(), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exchange",
            "tradingsymbol",
            "segment",
            "instrument_type",
            name="uq_instrument_master_symbol",
        ),
    )
    op.create_index(
        op.f("ix_instrument_master_exchange"), "instrument_master", ["exchange"], unique=False
    )
    op.create_index(
        op.f("ix_instrument_master_instrument_token"),
        "instrument_master",
        ["instrument_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instrument_master_tradingsymbol"),
        "instrument_master",
        ["tradingsymbol"],
        unique=False,
    )
    op.create_table(
        "price_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "trade_date", "source", name="uq_price_daily_symbol_date"),
    )
    op.create_index(op.f("ix_price_daily_symbol"), "price_daily", ["symbol"], unique=False)
    op.create_index(op.f("ix_price_daily_trade_date"), "price_daily", ["trade_date"], unique=False)
    op.create_table(
        "signal_audit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("signal_name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("strength", sa.String(length=40), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("trigger_price", sa.Float(), nullable=True),
        sa.Column("entry_zone_low", sa.Float(), nullable=True),
        sa.Column("entry_zone_high", sa.Float(), nullable=True),
        sa.Column("stop_loss", sa.Float(), nullable=True),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.Column("risk_reward", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("rsi_14", sa.Float(), nullable=True),
        sa.Column("ema_20", sa.Float(), nullable=True),
        sa.Column("ema_50", sa.Float(), nullable=True),
        sa.Column("ema_200", sa.Float(), nullable=True),
        sa.Column("relative_volume", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scan_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "as_of_date", "signal_name", "source", name="uq_signal_audit_observation"
        ),
    )
    op.create_index(
        op.f("ix_signal_audit_as_of_date"), "signal_audit", ["as_of_date"], unique=False
    )
    op.create_index(
        op.f("ix_signal_audit_signal_name"), "signal_audit", ["signal_name"], unique=False
    )
    op.create_index(op.f("ix_signal_audit_symbol"), "signal_audit", ["symbol"], unique=False)
    op.create_table(
        "stock_universe",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("exchange", sa.String(length=16), nullable=False),
        sa.Column("isin", sa.String(length=32), nullable=True),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("industry", sa.String(length=160), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("market_cap_bucket", sa.String(length=32), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("delisting_date", sa.Date(), nullable=True),
        sa.Column("index_membership", sa.Text(), nullable=True),
        sa.Column("index_entry_date", sa.Date(), nullable=True),
        sa.Column("index_exit_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isin"),
    )
    op.create_index(
        op.f("ix_stock_universe_market_cap_bucket"),
        "stock_universe",
        ["market_cap_bucket"],
        unique=False,
    )
    op.create_index(op.f("ix_stock_universe_sector"), "stock_universe", ["sector"], unique=False)
    op.create_index(op.f("ix_stock_universe_symbol"), "stock_universe", ["symbol"], unique=True)
    op.create_table(
        "technical_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("rsi_14", sa.Float(), nullable=True),
        sa.Column("macd", sa.Float(), nullable=True),
        sa.Column("macd_signal", sa.Float(), nullable=True),
        sa.Column("macd_hist", sa.Float(), nullable=True),
        sa.Column("atr_14", sa.Float(), nullable=True),
        sa.Column("atr_pct", sa.Float(), nullable=True),
        sa.Column("relative_volume", sa.Float(), nullable=True),
        sa.Column("sma_20", sa.Float(), nullable=True),
        sa.Column("sma_50", sa.Float(), nullable=True),
        sa.Column("sma_100", sa.Float(), nullable=True),
        sa.Column("sma_200", sa.Float(), nullable=True),
        sa.Column("ema_20", sa.Float(), nullable=True),
        sa.Column("ema_50", sa.Float(), nullable=True),
        sa.Column("ema_100", sa.Float(), nullable=True),
        sa.Column("ema_200", sa.Float(), nullable=True),
        sa.Column("ma_stack_status", sa.String(length=40), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "as_of_date", "source", name="uq_technical_snapshot_symbol_date"
        ),
    )
    op.create_index(
        op.f("ix_technical_snapshots_as_of_date"),
        "technical_snapshots",
        ["as_of_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_snapshots_symbol"), "technical_snapshots", ["symbol"], unique=False
    )
    op.create_table(
        "universe_scan_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("universe_name", sa.String(length=120), nullable=False),
        sa.Column("requested_symbols", sa.Integer(), nullable=False),
        sa.Column("successful_symbols", sa.Integer(), nullable=False),
        sa.Column("failed_symbols", sa.Integer(), nullable=False),
        sa.Column("lookback_days", sa.Integer(), nullable=False),
        sa.Column("min_score_filter", sa.Float(), nullable=True),
        sa.Column("min_signals_filter", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_universe_scan_runs_universe_name"),
        "universe_scan_runs",
        ["universe_name"],
        unique=False,
    )
    op.create_table(
        "daily_refresh_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("universe_name", sa.String(length=120), nullable=False),
        sa.Column("requested_symbols", sa.Integer(), nullable=False),
        sa.Column("successful_symbols", sa.Integer(), nullable=False),
        sa.Column("failed_symbols", sa.Integer(), nullable=False),
        sa.Column("price_rows_upserted", sa.Integer(), nullable=False),
        sa.Column("technical_rows_upserted", sa.Integer(), nullable=False),
        sa.Column("signal_rows_saved", sa.Integer(), nullable=False),
        sa.Column("instrument_rows_upserted", sa.Integer(), nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["universe_scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_refresh_runs_universe_name"),
        "daily_refresh_runs",
        ["universe_name"],
        unique=False,
    )
    op.create_table(
        "fundamentals_annual",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.Column("gross_profit", sa.Float(), nullable=True),
        sa.Column("ebitda", sa.Float(), nullable=True),
        sa.Column("ebit", sa.Float(), nullable=True),
        sa.Column("net_income", sa.Float(), nullable=True),
        sa.Column("eps", sa.Float(), nullable=True),
        sa.Column("book_value", sa.Float(), nullable=True),
        sa.Column("operating_cash_flow", sa.Float(), nullable=True),
        sa.Column("capital_expenditure", sa.Float(), nullable=True),
        sa.Column("free_cash_flow", sa.Float(), nullable=True),
        sa.Column("debt", sa.Float(), nullable=True),
        sa.Column("net_debt", sa.Float(), nullable=True),
        sa.Column("cash_and_equivalents", sa.Float(), nullable=True),
        sa.Column("total_assets", sa.Float(), nullable=True),
        sa.Column("total_liabilities", sa.Float(), nullable=True),
        sa.Column("current_assets", sa.Float(), nullable=True),
        sa.Column("current_liabilities", sa.Float(), nullable=True),
        sa.Column("retained_earnings", sa.Float(), nullable=True),
        sa.Column("shares_outstanding", sa.Float(), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("enterprise_value", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stock_universe.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "fiscal_year", "source", name="uq_fundamentals_annual"),
    )
    op.create_index(
        op.f("ix_fundamentals_annual_symbol"), "fundamentals_annual", ["symbol"], unique=False
    )
    op.create_table(
        "fundamentals_quarterly",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("fiscal_quarter", sa.Integer(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.Column("ebitda", sa.Float(), nullable=True),
        sa.Column("ebit", sa.Float(), nullable=True),
        sa.Column("net_income", sa.Float(), nullable=True),
        sa.Column("eps", sa.Float(), nullable=True),
        sa.Column("operating_cash_flow", sa.Float(), nullable=True),
        sa.Column("free_cash_flow", sa.Float(), nullable=True),
        sa.Column("total_assets", sa.Float(), nullable=True),
        sa.Column("total_liabilities", sa.Float(), nullable=True),
        sa.Column("shares_outstanding", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("fiscal_quarter between 1 and 4", name="ck_fiscal_quarter_range"),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stock_universe.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "fiscal_year", "fiscal_quarter", "source", name="uq_fundamentals_quarterly"
        ),
    )
    op.create_index(
        op.f("ix_fundamentals_quarterly_symbol"), "fundamentals_quarterly", ["symbol"], unique=False
    )
    op.create_table(
        "research_watchlist_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("watchlist_name", sa.String(length=120), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("source_universe", sa.String(length=120), nullable=True),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("tags", sa.String(length=240), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_run_id"],
            ["universe_scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "watchlist_name", "symbol", name="uq_research_watchlist_item"
        ),
    )
    op.create_index(
        op.f("ix_research_watchlist_items_symbol"),
        "research_watchlist_items",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_watchlist_items_watchlist_name"),
        "research_watchlist_items",
        ["watchlist_name"],
        unique=False,
    )
    op.create_table(
        "universe_scan_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=True),
        sa.Column("band", sa.String(length=40), nullable=True),
        sa.Column("fundamentals_score", sa.Float(), nullable=True),
        sa.Column("technicals_score", sa.Float(), nullable=True),
        sa.Column("flows_score", sa.Float(), nullable=True),
        sa.Column("events_quality_score", sa.Float(), nullable=True),
        sa.Column("macro_sector_score", sa.Float(), nullable=True),
        sa.Column("active_signal_count", sa.Integer(), nullable=False),
        sa.Column("active_signals_json", sa.Text(), nullable=False),
        sa.Column("last_close", sa.Float(), nullable=True),
        sa.Column("rsi_14", sa.Float(), nullable=True),
        sa.Column("ma_stack", sa.String(length=40), nullable=True),
        sa.Column("data_quality_warnings_json", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["universe_scan_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "symbol", name="uq_universe_scan_result_symbol"),
    )
    op.create_index(
        op.f("ix_universe_scan_results_run_id"), "universe_scan_results", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_universe_scan_results_symbol"), "universe_scan_results", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_universe_scan_results_symbol"), table_name="universe_scan_results")
    op.drop_index(op.f("ix_universe_scan_results_run_id"), table_name="universe_scan_results")
    op.drop_table("universe_scan_results")
    op.drop_index(
        op.f("ix_research_watchlist_items_watchlist_name"), table_name="research_watchlist_items"
    )
    op.drop_index(op.f("ix_research_watchlist_items_symbol"), table_name="research_watchlist_items")
    op.drop_table("research_watchlist_items")
    op.drop_index(op.f("ix_fundamentals_quarterly_symbol"), table_name="fundamentals_quarterly")
    op.drop_table("fundamentals_quarterly")
    op.drop_index(op.f("ix_fundamentals_annual_symbol"), table_name="fundamentals_annual")
    op.drop_table("fundamentals_annual")
    op.drop_index(op.f("ix_daily_refresh_runs_universe_name"), table_name="daily_refresh_runs")
    op.drop_table("daily_refresh_runs")
    op.drop_index(op.f("ix_universe_scan_runs_universe_name"), table_name="universe_scan_runs")
    op.drop_table("universe_scan_runs")
    op.drop_index(op.f("ix_technical_snapshots_symbol"), table_name="technical_snapshots")
    op.drop_index(op.f("ix_technical_snapshots_as_of_date"), table_name="technical_snapshots")
    op.drop_table("technical_snapshots")
    op.drop_index(op.f("ix_stock_universe_symbol"), table_name="stock_universe")
    op.drop_index(op.f("ix_stock_universe_sector"), table_name="stock_universe")
    op.drop_index(op.f("ix_stock_universe_market_cap_bucket"), table_name="stock_universe")
    op.drop_table("stock_universe")
    op.drop_index(op.f("ix_signal_audit_symbol"), table_name="signal_audit")
    op.drop_index(op.f("ix_signal_audit_signal_name"), table_name="signal_audit")
    op.drop_index(op.f("ix_signal_audit_as_of_date"), table_name="signal_audit")
    op.drop_table("signal_audit")
    op.drop_index(op.f("ix_price_daily_trade_date"), table_name="price_daily")
    op.drop_index(op.f("ix_price_daily_symbol"), table_name="price_daily")
    op.drop_table("price_daily")
    op.drop_index(op.f("ix_instrument_master_tradingsymbol"), table_name="instrument_master")
    op.drop_index(op.f("ix_instrument_master_instrument_token"), table_name="instrument_master")
    op.drop_index(op.f("ix_instrument_master_exchange"), table_name="instrument_master")
    op.drop_table("instrument_master")
    op.drop_index(op.f("ix_delivery_data_trade_date"), table_name="delivery_data")
    op.drop_index(op.f("ix_delivery_data_symbol"), table_name="delivery_data")
    op.drop_table("delivery_data")
    op.drop_index(op.f("ix_corporate_actions_symbol"), table_name="corporate_actions")
    op.drop_index(op.f("ix_corporate_actions_ex_date"), table_name="corporate_actions")
    op.drop_table("corporate_actions")
    op.drop_index(op.f("ix_composite_scores_symbol"), table_name="composite_scores")
    op.drop_index(op.f("ix_composite_scores_as_of_date"), table_name="composite_scores")
    op.drop_table("composite_scores")
    op.drop_index(op.f("ix_bulk_block_deals_symbol"), table_name="bulk_block_deals")
    op.drop_index(op.f("ix_bulk_block_deals_deal_date"), table_name="bulk_block_deals")
    op.drop_table("bulk_block_deals")
    # ### end Alembic commands ###
